### ISSUE TITLE
Compile Issue with Std.is(callback, Void -> Void)) 

### ISSUE THREAD

**Issue by tsmithf** [peteshand/notifier#1]
Haxe 3.4.7
Openfl: 8.9.1
Lime: 7.5.0
Notifier: 1.0.6

Trying to use Delay, which utilities notifier, but it won't compile...

C:/HaxeToolkit/haxe/lib/notifier/1,0,6/src/notifier/Notifier.hx:81: characters 28-30 : Unexpected ->

Which relates to the line...
if (Std.is(callback, Void -> Void)) {

**Comment by peteshand** [comment]
Hi there
What version of Haxe are you using? I'm guessing 3.x?

**Comment by peteshand** [comment]
Also what platform are you targeting?

**Comment by peteshand** [comment]
Haxe3 function check try catch added to version 1.0.7
https://lib.haxe.org/p/notifier/

**Comment by tsmithf** [comment]
Hi Pete,

I am on Haxe 3.4.7 and targeting html5. Currently developing on windows 10 using HaxeDevelop.

I managed a work around, but probably not ideal, swapping the following…

/*
if (Std.is(callback, Void -> Void)) {
                callback0 = untyped callback;
                callback0();
} else {
                callback1 = untyped callback;
                callback1(value);
}
*/

if (Type.typeof(callback) == TFunction) {
                callback1 = untyped callback;
                callback1(value);
} else {
                callback0 = untyped callback;
                callback0();
}
[X]

Trevor Smith
Circle Courtyard   4a Castle Street   Farnham   Surrey   GU9 7HR

t 01252 711700

f 01252 711707

m 07909 967504

**Comment by peteshand** [comment]
Won't that always result in callback1 being called?
At any rate, if it works for you like that then great.

I'd recommend upgrading to haxe 4, even thought its still in rc, over 70% of dev have already made the switch.
