### ISSUE TITLE
Complex Example

### ISSUE THREAD

**Issue by benjamin-stern** [peteshand/notifier#2]
I saw listing in the readme that it can support complex objects as well? Do you have an example of it to see how it can function is such cases if an object is something other than base type?

so if i have a class with properties, will it be able to determine that any of the properties have changed? Or is it just that the instance has been changed?

**Comment by peteshand** [comment]
Hey @benjstern 

Yes complex objects will work.
However, no.. if you set sub-property there is no way for the notifier to be aware of this.
You can manually trigger a dispatch

Example of complete object, setting sub properties and manual dispatch
```
class Main {
	static public function main():Void {
		var notifier = new Notifier<Point>();
		notifier.add((point) -> {
			trace('x = ' + point.x);
		});
        	notifier.value = {x: 2, y: 3}; // this will trigger a trace of 'x = 2

        	notifier.value.x = 5; // this will update the x property, however will not trigger a dispatch
        	notifier.dispatch(); // this will trigger a trace of 'x = 5'

	}
}

typedef Point = {
	x:Float,
	y:Float
}

```
